CREATE OR REPLACE TABLE DOC_AI_DB.PUBLIC.BILL_OF_LANDINGS (
	ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
	ORGANIZATION VARCHAR(500),
	INVOICENO VARIANT,
	GROSSWEIGHT DECIMAL(15,3),
	MEASUREMENT DECIMAL(15,3),
	TOTALCARTON NUMBER(10,0),
	SOURCE VARCHAR(500),
	SOURCEID VARCHAR(100),
	ONBOARDDATE DATE,
	VESSEL VARCHAR(500),
	PACKAGE_CODE VARIANT,
	PACKAGE_DESCRIPTION VARIANT,
	CREATEDAT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATEDAT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);