-- INVOICES table schema (corrected)
CREATE OR REPLACE TABLE DOC_AI_DB.PUBLIC.INVOICES (
	ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
	ITEMS VARIANT,
	INVOICENO VARCHAR(16777216),
	PONUMBER VARCHAR(50) NOT NULL,
	VENDORNAME VARCHAR(50),
	CURRENCY VARCHAR(50),
	PAGES VARIANT,
	SOURCE VARCHAR(16777216),
	SOURCEID VARCHAR(16777216),
	ORGANIZATION VARCHAR(16777216),
	CREATEDAT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATEDAT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- INVOICE_ITEMS table schema (corrected)
CREATE OR REPLACE TABLE DOC_AI_DB.PUBLIC.INVOICE_ITEMS (
	ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
	PONO VARCHAR(50) NOT NULL,
	ITEMCODE VARCHAR(50),
	QUANTITY NUMBER(38,0),
	LINEAMOUNT NUMBER(38,0),
	UNITPRICE NUMBER(38,0),
	VALIDITEM BOOLEAN,
	MATCH_ERP BOOLEAN,
	MATCH BOOLEAN,
	SKIP BOOLEAN,
	INVOICEID VARCHAR(16777216),
	CREATEDAT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATEDAT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- Sample data insertion queries (optional)
-- INSERT INTO DOC_AI_DB.PUBLIC.INVOICES (INVOICENO, PONUMBER, VENDORNAME, CURRENCY, SOURCE, ORGANIZATION)
-- VALUES ('INV-001', 'PO-12345', 'SoftwareOne', 'USD', 'invoice_001', 'SoftwareOne Indonesia');

-- INSERT INTO DOC_AI_DB.PUBLIC.INVOICE_ITEMS (PONO, ITEMCODE, QUANTITY, UNITPRICE, LINEAMOUNT, VALIDITEM, MATCH_ERP, MATCH, SKIP, INVOICEID)
-- VALUES ('PO-12345', 'ITEM-001', 10, 100, 1000, TRUE, TRUE, TRUE, FALSE, '1');